version: "2"
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
plugins:
  csslint:
    enabled: true
  editorconfig:
    enabled: true
    checks:
      END_OF_LINE:
        enabled: false
      INDENTATION_SPACES:
        enabled: false
      INDENTATION_SPACES_AMOUNT:
        enabled: false
      TRAILINGSPACES:
        enabled: false
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      config: app/.eslintrc.js
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD029:
        enabled: false
      MD046:
        enabled: false
  nodesecurity:
    enabled: true
  sass-lint:
    enabled: true
