// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace VCAuthn.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20190926051508_update-session-persistance")]
    partial class updatesessionpersistance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VCAuthn.IdentityServer.SessionStorage.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiredTimestamp");

                    b.Property<string>("PresentationRecordId");

                    b.Property<string>("PresentationRequestId");

                    b.Property<bool>("PresentationRequestSatisfied");

                    b.Property<string>("Proof");

                    b.Property<string>("RequestParams");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VCAuthn.PresentationConfiguration.PresentationRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Config");

                    b.Property<string>("SubjectIdentifier");

                    b.HasKey("Id");

                    b.ToTable("PresentationConfigurations");
                });

            modelBuilder.Entity("VCAuthn.UrlShortener.MappedUrl", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("Key");

                    b.ToTable("MappedUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
