// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VCAuthn.Migrations;

namespace VCAuthn.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20201005200901_v3Models")]
    partial class v3Models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VCAuthn.Models.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiredTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PresentationRecordId")
                        .HasColumnType("text");

                    b.Property<string>("PresentationRequest")
                        .HasColumnType("text");

                    b.Property<string>("PresentationRequestId")
                        .HasColumnType("text");

                    b.Property<bool>("PresentationRequestSatisfied")
                        .HasColumnType("boolean");

                    b.Property<string>("_presentation")
                        .HasColumnName("Proof")
                        .HasColumnType("text");

                    b.Property<string>("_presentationRequest")
                        .HasColumnName("ProofRequest")
                        .HasColumnType("text");

                    b.Property<string>("_requestParameters")
                        .HasColumnName("RequestParams")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VCAuthn.Models.MappedUrl", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("MappedUrls");
                });

            modelBuilder.Entity("VCAuthn.Models.PresentationConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("SubjectIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("_configuration")
                        .HasColumnName("Config")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PresentationConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
