[tool.poetry]
name = "acapy-vc-authn-oidc"
version = "0.2.2"
description = "Verifiable Credential Identity Provider for OpenID Connect."
authors = ["Government of British Columbia <[DItrust@gov.bc.ca](mailto:DItrust@gov.bc.ca)>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
            "Programming Language :: Python :: 3",
            "License :: OSI Approved :: Apache Software License",
	        "Operating System :: OS Independent",
]
repository = "https://github.com/openwallet-foundation/acapy-vc-authn-oidc"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = "^0.115.4"
jinja2 = "^3.1.4"
oic = "^1.7.0"
pymongo = "^4.10.1"
pyop = "^3.4.1"
python-multipart = "^0.0.18" # required by fastapi to serve/upload files
qrcode = { version = "^8.0", extras = ["pil"]}
structlog = "^24.4.0"
uvicorn = { version = "^0.32.0", extras = ["standard"] }
python-socketio = "^5.11.4" # required to run websockets
canonicaljson = "^2.0.0" # used to provide unique consistent user identifiers"
pydantic-settings = "^2.6.1"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
mock = "^5.1.0"
mongomock = "^4.1.2"
pytest-asyncio = "^0.24.0"
pytest-cov = "^6.0.0"
pytest = "^8.3.3"
requests-mock = "^1.12.1"
setuptools = "^75.3.0"

[tool.pytest.ini_options]
testpaths = "oidc-controller"
asyncio_default_fixture_loop_scope = "function"

[tool.pyright]
pythonVersion = "3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
