kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Build template for an Aries Cloudagent .
    tags: python, hyperledger
    iconClass: icon-python
  name: ${PREFIX}${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${PREFIX}${NAME}
      labels:
        name: ${PREFIX}${NAME}
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
        app-group: ${APP_GROUP}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${PREFIX}${NAME}
      labels:
        name: ${PREFIX}${NAME}
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
        app-group: ${APP_GROUP}
    spec:
      runPolicy: Serial
      source:
        type: Git
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO_URL}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: ${SOURCE_IMAGE_NAME}
          dockerfilePath: ${DOCKER_FILE_PATH}
      output:
        to:
          kind: ImageStreamTag
          name: ${PREFIX}${NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
      triggers:
        - type: ConfigChange

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.  You should keep this as default unless your know what your doing.
    required: true
    value: agent
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: vc-authn-oidc
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the components in this project.
    required: true
    value: vc-authn-oidc
  - name: PREFIX
    displayName: Prefix
    description: A name prefix used for all objects
    required: false
    value: vc-authn-
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo, don't use the this default unless your just experimenting.
    required: true
    value: https://github.com/bcgov/vc-authn-oidc.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: main
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
    value: docker/agent
  - name: DOCKER_FILE_PATH
    displayName: Docker File Path
    description: The path to the docker file defining the build.
    required: false
    value: Dockerfile
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the Docker image to be used for the build. Overrides the FROM instruction in the Dockerfile.
    required: false
    value: artifacts.developer.gov.bc.ca/docker-remote/bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3-rc0
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 500Mi
