#!/bin/bash

# set -x

# Setup variables for PWD
if [ $PWD_HOST_FQDN == "labs.play-with-docker.com" ]
    then
        export ETH_CONFIG="eth1"
    elif [ $PWD_HOST_FQDN == "play-with-docker.vonx.io" ]
    then
        export ETH_CONFIG="eth0"
    else
        export ETH_CONFIG="eth0"
fi
myhost=`ifconfig ${ETH_CONFIG} | grep inet | cut -d':' -f2 | cut -d' ' -f1 | sed 's/\./\-/g'`
export DEMO_APP_URL="http://ip${myhost}-${SESSION_ID}-8080.direct.${PWD_HOST_FQDN}"
export NGROK_AGENT_URL="http://ip${myhost}-${SESSION_ID}-5679.direct.${PWD_HOST_FQDN}"
export NGROK_CONTROLLER_URL="http://ip${myhost}-${SESSION_ID}-5001.direct.${PWD_HOST_FQDN}"

echo Get S2I
curl -L https://github.com/openshift/source-to-image/releases/download/v1.2.0/source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

echo Update appsettings.json
export APPSETTINGS=../oidc-controller/src/VCAuthn/appsettings.json
cp ${APPSETTINGS} ${APPSETTINGS}.bck
sed -i "37,37s#http://localhost:8080#${DEMO_APP_URL}#" ${APPSETTINGS}

echo Verify update to appsettings file
diff ${APPSETTINGS} ${APPSETTINGS}.bck

echo Build vc-authn
pushd ../docker
./manage build

echo Deploy vc-authn
./manage start-demo

# Back to demo folder
popd

# Add the Presentation Request to VC Authn. Loop until container is ready
export CONTROLLER_WAIT=10
echo Looping for the controller to be initialized -- ${CONTROLLER_WAIT} seconds between tries
until ./updatePresentation --new presentationRequest.json
do
  sleep ${CONTROLLER_WAIT}
done

echo Build demo app
pushd ../demo/docker
./manage build

echo Deploy demo app
./manage start
popd

echo Check what docker containers are running
docker ps
