"""remove storage of presention_exchange object

Revision ID: bbf9bd9a8875
Revises: 65eab74c2e3c
Create Date: 2023-01-24 21:09:31.039947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbf9bd9a8875'
down_revision = '65eab74c2e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sess_auth_sessions', 'presentation_exchange')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sess_auth_sessions', sa.Column('presentation_exchange', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
