@startuml "vc-authn-oidc-flow"
actor User
entity UserAgent
entity RP
entity OP
entity IdentityWallet

User -> UserAgent: Naviagates to RP website
UserAgent -> RP: Fetch RP website
RP --> UserAgent: Return website
User -> UserAgent: Click "vc-authn challenge" button (e.g verify your age)

group Challenge Method
    alt UserAgent Generated Challenge
        UserAgent -> UserAgent: Generate OIDC VC-Authn request  
        UserAgent -> OP: Redirect to OIDC VC-Authn request
    end

    alt RP Generated Challenge
        UserAgent -> RP: Create OIDC VC-Authn request
        RP --> UserAgent: Redirect to OIDC VC-Authn request  
        UserAgent -> OP: Follow OIDC VC-Authn request  
    end
end

OP -> OP: Generate VC Presentation Request
OP -> UserAgent: Return VC Presentation Request

group IdentityWallet Communication Method
    alt QR Code Scanned By IdentityWallet
        loop UserAgent await IdentityWallet response
            UserAgent -> OP: Request challenge status
            OP --> UserAgent: "authentication_pending" response
        end
        note left: The UserAgent polls the OP until the IdentityWallet responds to the request
        UserAgent -> IdentityWallet: Request Scanned
        IdentityWallet -> IdentityWallet: Request validated
        IdentityWallet -> User  : Present verify data request
        User -> IdentityWallet : Clicks accept request
        IdentityWallet -> IdentityWallet : Generate VC presentation
        IdentityWallet -> OP : Submit VC presentation
        UserAgent -> OP: Request challenge status
    end

    alt Deeplink invoked by IdentityWallet
        UserAgent -> IdentityWallet: Deeplink invoked
        IdentityWallet -> IdentityWallet: Request validated
        IdentityWallet -> User  : Present verify data request
        User -> IdentityWallet : Clicks accept request
        IdentityWallet -> IdentityWallet : Generate VC presentation
        IdentityWallet -> OP : Submit VC presentation
        IdentityWallet -> UserAgent: Redirect to OP URI
        UserAgent -> OP: Follow redirect
    end
end

group OAuth Flow
    alt Implicit Flow
        OP -> UserAgent: Redirect request to RP redirect URI with authorization code
        UserAgent -> RP: Follow redirect with authorization code
        RP -> OP: Request token with authorization code
        OP --> RP: Token response
    end

    alt Authorization Code Flow
        OP -> UserAgent: Redirect request to RP redirect URI with token
        UserAgent -> RP: Follow redirect with token
    end
end

RP --> UserAgent: Success web page
UserAgent --> User: ACK

@enduml