{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "global.fullname" . }}-db
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the controller to the db, and between db pods
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "vc-authn-oidc.selectorLabels" . | nindent 14 }}
        - podSelector:
            {{- with .Values.mongodb.commonLabels }}
            matchLabels:
              {{- toYaml . | nindent 14 }}
            {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.mongodb.service.ports.mongodb }}
  podSelector:
    {{- with .Values.mongodb.commonLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "acapy.fullname" . }}-db
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  # Allow traffic from the agent to the db
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "acapy.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgresql.primary.service.ports.postgresql }}
  podSelector:
    {{- with .Values.postgresql.commonLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
