{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "global.fullname" . }}-agent-webhook
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the agent to the controller
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ include "acapy.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
---
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "global.fullname" . }}-agent-access
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the controller to the agent
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "vc-authn-oidc.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.acapy.service.adminPort }}
  podSelector:
    matchLabels:
      {{ include "acapy.selectorLabels" . | nindent 6 }}
{{- end }}
